version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    groups:
      kubernetes-modules:
        patterns: ["k8s.io/api", "k8s.io/apimachinery", "k8s.io/client-go"]
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
