apiVersion: v1
kind: ServiceAccount
metadata:
  name: runnerscout
  namespace: runnerscout
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runnerscout
  namespace: runnerscout
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, list, create, update]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, create, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runnerscout
  namespace: runnerscout
subjects:
  - kind: ServiceAccount
    name: runnerscout
    namespace: runnerscout
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runnerscout
